#nullable enable
using System;
using System.ComponentModel.DataAnnotations;

namespace ServiceWithHangfire
{
    public class FeedLog
    {
        [Key]
        public uint id { get; set; }
        public string? log_record_type { get; set; }
        public uint? log_contact_id { get; set; }
        public uint? log_user_id { get; set; }
        public string? log_type { get; set; }
        public ulong? verify_uuid { get; set; }
        public uint? contact_id { get; set; }
        public uint? company_id { get; set; }
        public uint? campaign_id { get; set; }
        public uint? list_id { get; set; }
        public uint? ext_list_id { get; set; }
        public uint? block_id { get; set; }
        public short? priority { get; set; }
        public short? feed_priority { get; set; }
        public short? status { get; set; }
        public string? approve_status { get; set; }
        public uint? phone_reason_id { get; set; }
        public uint? self_phone_reason_id { get; set; }
        public uint? pv_status_id { get; set; }
        public short? locked { get; set; }
        public DateTime? locked_at { get; set; }
        public uint? locked_by { get; set; }
        public DateTime? locked_since { get; set; }
        public short? company_locked { get; set; }
        public DateTime? company_locked_at { get; set; }
        public uint? company_locked_by { get; set; }
        public DateTime? company_locked_since { get; set; }
        public int? job_level { get; set; }
        public uint? comment_id { get; set; }
        public string? asset { get; set; }
        public string? tag { get; set; }
        public string? answers { get; set; }
        public DateTime? date { get; set; }
        public DateTime? pv_date { get; set; }
        public string? report_status { get; set; }
        public uint? country_country_id { get; set; }
        public string? status_title { get; set; }
        public string? proof_link { get; set; }
        public string? locked_by_user_name { get; set; }
        public string? locked_by_user_pid { get; set; }
        public string? company_locked_by_user_name { get; set; }
        public string? company_locked_by_user_pid { get; set; }
        public string? lv_online_user_name { get; set; }
        public string? lv_online_user_pid { get; set; }
        public string? lv_online_user_pid_with_name { get; set; }
        public string? lv_phone_user_name { get; set; }
        public string? lv_phone_user_pid { get; set; }
        public string? lv_phone_user_pid_with_name { get; set; }
        public uint? assigned_to_user_id { get; set; }
        public uint? ov_status_id { get; set; }
        public uint? self_ov_status_id { get; set; }
        public string? ov_status_short_name { get; set; }
        public string? ov_status_long_name { get; set; }
        public string? phone_reason { get; set; }
        public DateTime? list_date { get; set; }
        public DateTime? created_at { get; set; }
        public DateTime? updated_at { get; set; }
        public DateTime? deleted_at { get; set; }
        public short? reported { get; set; }
        public short? reported_template { get; set; }
        public DateTime? phone_verified { get; set; }
        public uint? domain_id { get; set; }
        public uint? lv_online_user_id { get; set; }
        public DateTime? lvo_date { get; set; }
        public int? lv_phone_user_id { get; set; }
        public short? final_approve { get; set; }
        public uint? cv_status_id { get; set; }
        public uint? main_industry_id { get; set; }
        public string? phone { get; set; }
        public short? phone_invalid { get; set; }
        public string? mobile_phone { get; set; }
        public string? industry_id { get; set; }
        public string? industry_type { get; set; }
        public string? industry_name { get; set; }
        public uint? sub_industry_id { get; set; }
        public string? sub_industry_type { get; set; }
        public string? sub_industry_name { get; set; }
        public string? sic_code { get; set; }
        public uint? company_employees { get; set; }
        public uint? company_employees_max { get; set; }
        public uint? company_revenue { get; set; }
        public uint? company_revenue_max { get; set; }
        public string? ov_comment { get; set; }
        public string? cv_comment { get; set; }
        public string? meta_data { get; set; }
        public string? country { get; set; }
        public string? reported_phone { get; set; }
        public string? assigned_users { get; set; }
        public string? custom_fields_values_contact { get; set; }
        public string? custom_fields_values_company { get; set; }
        public string? company_meta { get; set; }
        public string? title_mapping { get; set; }
        public uint? lv_company_user_id { get; set; }
        public string? lv_company_user_name { get; set; }
        public string? lv_company_user_pid { get; set; }
        public string? lv_company_user_pid_with_name { get; set; }
        public string? unlock_cause { get; set; }
        public uint? previous_pv_comment_id { get; set; }
        public int? email_elt { get; set; }
        public DateTime? previous_ov_date { get; set; }
        public DateTime? address_date { get; set; }
        public DateTime? log_created_at { get; set; }
        public uint? list_industry_id { get; set; }
        public string? list_industry_name { get; set; }
        public uint? list_sub_industry_id { get; set; }
        public string? list_sub_industry_name { get; set; }
        public short? non_retrievable { get; set; }
        public int? lvo { get; set; }
        public int? lvp { get; set; }
        public int? lvc { get; set; }
        public int? dro { get; set; }
        public int? cm_status { get; set; }
        public short? geo_is_valid { get; set; }
        public uint? qc_check_ov_earliest_id { get; set; }
        public uint? qc_check_ov_latest_id { get; set; }
        public uint? qc_check_ov_company_earliest_id { get; set; }
        public uint? qc_check_ov_company_latest_id { get; set; }
        public uint? qc_check_pv_earliest_id { get; set; }
        public uint? qc_check_pv_latest_id { get; set; }
        public uint? qc_reaction_ov_id { get; set; }
        public uint? qc_reaction_ov_company_id { get; set; }
        public uint? qc_reaction_pv_id { get; set; }
        public uint? qc_reserve_ov_user_id { get; set; }
        public uint? qc_reserve_pv_user_id { get; set; }
        public uint? qc_skip_ov_user_id { get; set; }
        public uint? qc_skip_pv_user_id { get; set; }
        public short? qc_has_recheck_by_ov { get; set; }
        public short? qc_has_recheck_by_pv { get; set; }
        public short? qc_has_old_strikes_by_ov { get; set; }
        public short? qc_has_old_strikes_by_ov_company { get; set; }
        public short? qc_has_old_strikes_by_pv { get; set; }
        public DateTime? cpv_date { get; set; }
        public uint? lead_type_id { get; set; }
        
    }
}
